global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "kafka-consumer"
    metrics_path: /metrics
    static_configs:
      - targets: ["consumer:8001"]

  - job_name: "csv-ingest"
    metrics_path: /metrics
    static_configs:
      - targets: ["csv-ingest:8002"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]